### ISSUE TITLE
controller.ino will not compile

### ISSUE THREAD

**Issue by wrexy1994** [Jaycar-Electronics/WiFi-Controlled-Strip-Lighting#1]
I assume that the variable 'rate' on line 76 is supposed to be 'currentRate'?

**Comment by Jaycar-Electronics** [comment]
cheers, you're right, slipped by from re-factoring.
fixed in https://github.com/Jaycar-Electronics/WiFi-Controlled-Strip-Lighting/commit/2a7d196b862226820ff4aa7e5d0ec53dc8784818
