### ISSUE TITLE
Color offsets

### ISSUE THREAD

**Issue by wrexy1994** [Jaycar-Electronics/WiFi-Controlled-Strip-Lighting#2]
I have found that in my setup, the colors need to be set BBRRGG, instead of RRGGBB. For example, to get blue on the solid/single, I need to enter FF0000. Any ideas?

**Comment by Jaycar-Electronics** [comment]
This is just gonna be related to the data ordering. 
If you look at line 51 of the ino, you'll see that it's set to NEO_RGB. try setting this to NEO_BRG; does this change? 

I'm not sure if the adafruit have BRG, so if you get "NEO_BRG" not defined, we'll have to look at either creating it or changing the order elsewhere.  I will try out later today.

**Comment by Jaycar-Electronics** [comment]
We've tried setting BRG in the controller.ino in the latest version 43e4996
 
let us know if that fixes it 

cheers
